name: Trigger Infra RC Deploy

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  dispatch-rc-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch RC Deploy Event to Infra Repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.GITHUB_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Sahil1709/finance-manager-infra/actions/workflows/nightly-build.yml/dispatches \
            -d '{"event_type": "rc_deploy"}'
