name: Trigger Infra RC Deploy

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '20'

      - name: Install Dependencies
        run: npm install

      - name: Run Semantic Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npm run release

  dispatch-rc-deploy:
    runs-on: ubuntu-latest
    needs: run-semantic-release
    steps:
      - name: Dispatch RC Deploy Event to Infra Repo
        run: |
          curl -L \
            -X POST \
            -H "Accept: application/vnd.github+json" \
            -H "Authorization: Bearer ${{ secrets.PAT_TOKEN }}" \
            -H "X-GitHub-Api-Version: 2022-11-28" \
            https://api.github.com/repos/Sahil1709/finance-manager-infra/actions/workflows/nightly-build.yml/dispatches \
            -d '{"ref":"main", "inputs": {"event_type": "rc-deploy"}}'
